### ISSUE TITLE
OD Max: ODM crashes with out of memory error when processing >500 spherical camera images 

### ISSUE THREAD

**Issue by TimeScience** [AuScalableDroneCloud/pipelines-jupyter#1]
Not sure the exact image count that crashed it, the test version runs to completion with 530 images, but when I tried to do 870 images from another video it crashed. error details below and full error log attached
[video to odm out of memory error.txt](https://github.com/AuScalableDroneCloud/pipelines-jupyter/files/8114358/video.to.odm.out.of.memory.error.txt)

...
_Adding edges 100%... done. (Took 1.308s)
1195262 total edges.
View selection:
Building BVH from 797004 faces... done. (Took: 638 ms)

Calculating face qualities 100%... done. (Took 62.571s)

Postprocessing face infos 100%... done. (Took 31.294s)
Killed

===== Dumping Info for Geeks (developers need this to fix bugs) =====
Child returned 137
Traceback (most recent call last):
File "/code/stages/odm_app.py", line 94, in execute
self.first_stage.run()
File "/code/opendm/types.py", line 340, in run
self.next_stage.run(outputs)
File "/code/opendm/types.py", line 340, in run
self.next_stage.run(outputs)
File "/code/opendm/types.py", line 340, in run
self.next_stage.run(outputs)
[Previous line repeated 4 more times]
File "/code/opendm/types.py", line 321, in run
self.process(self.args, outputs)
File "/code/stages/mvstex.py", line 108, in process
system.run('"{bin}" "{nvm_file}" "{model}" "{out_dir}" '
File "/code/opendm/system.py", line 106, in run
raise SubprocessException("Child returned {}".format(retcode), retcode)
opendm.system.SubprocessException: Child returned 137

===== Done, human-readable information to follow... =====

[ERROR]   Whoops! You ran out of memory! Add more RAM to your computer, if you're using docker configure it to use more memory, for WSL2 make use of .wslconfig (https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig), resize your images, lower the quality settings or process the images using a cloud provider (e.g. https://webodm.net).
100 - done._

**Comment by spsaswat** [comment]
Closing the issue, since issues are being tracker in the tracker repository.
